name: refocus_app
description: "A clean Flutter project for ReFocus app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # UI & Fonts
  google_fonts: ^6.1.0
  lottie: ^2.2.0

  # Permissions & Usage
  usage_stats: ^1.3.1
  flutter_foreground_task: ^9.1.0
  
  # Authentication & Location
  local_auth: ^2.3.0
  geolocator: ^13.0.1

  flutter_local_notifications: ^17.0.0

  # Cupertino Icons
  cupertino_icons: ^1.0.8


  shared_preferences: ^2.2.2
  
  # Secure Storage for encrypted PIN and password
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

  # Charts for statistics visualization
  fl_chart: ^0.68.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/img/
    - assets/
    - assets/training_data.csv
    

